#!/bin/bash

# Script to help add images to the project
# Usage: ./scripts/add-images.sh

echo "📸 Image Setup Helper for Shri Shirdi Sai Baba Temple"
echo "=================================================="
echo ""
echo "Please add your temple images to: public/images/"
echo ""
echo "Required image filenames for the carousel:"
echo "1. white-hibiscus.jpg"
echo "2. temple-exterior-1.jpg"
echo "3. temple-path-1.jpg"
echo "4. temple-garden-1.jpg"
echo "5. temple-path-2.jpg"
echo "6. temple-exterior-2.jpg"
echo "7. temple-exterior-3.jpg"
echo "8. temple-nature-1.jpg"
echo "9. temple-entrance-path.jpg"
echo "10. coconut-tree.jpg"
echo "11. temple-nature-2.jpg"
echo "12. temple-lights-1.jpg"
echo "13. temple-lights-2.jpg"
echo "14. temple-lights-3.jpg"
echo "15. temple-development.jpg"
echo "16. temple-garden-2.jpg"
echo "17. temple-nature-3.jpg"
echo "18. temple-lights-4.jpg"
echo "19. temple-vegetation.jpg"
echo "20. temple-nature-4.jpg"
echo ""
echo "Current images in public/images/:"
ls -lh public/images/*.{jpg,jpeg,png,webp} 2>/dev/null || echo "No images found yet"
echo ""
echo "After adding images, refresh your browser to see them in the carousel!"
